version: "3"

services:

  database:
    build: 
       context: ./database
    image: mobystore_db
    # set default mysql root password, change as needed
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD: gordonpassword
      POSTGRES_DB: mobystore
    # Expose port 3306 to host. Not for the application but
    # handy to inspect the database from the host machine.
    ports:
      - "5432:5432" 
    restart: always

  appserver:
    build:
       context: ./app
    image: mobystore_app
    # mount point for application in tomcat
    links:
      - database:mobystore_db
    # open ports for tomcat and remote debugging
    ports:
      - "8080:8080" 
    restart: always

