version: "3.1"

services:
  database:
    build: 
       context: ./database
    image: atsea_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password
    #restart: always

  appserver:
    build:
       context: .
       dockerfile: app/Dockerfile
    image: atsea_app
    # mount point for application in tomcat
    links:
      - database:atsea_db
    # open ports for tomcat and remote debugging
    ports:
      - "8080:8080" 
    networks:
      - front-tier
      - back-tier
    volumes:
      - ./app/static:/static
    secrets:
      - postgres_password
    #restart: always
    volumes:
     - ./app/static:/static

networks:
  front-tier:
  back-tier:

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
