version: "3"

services:
  database:
    #build: 
    #   context: ./database
    image: mobystore_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD: gordonpassword
      POSTGRES_DB: mobystore
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    deploy:
      placement:
        constraints: [node.role == manager]

  appserver:
    #build:
    #   context: ./app
    image: mobystore_app
    #links: database
    #depends_on:
    #  - database
    ports:
      - "8080:8080" 
    networks:
      - front-tier
      - back-tier
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]
  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8001:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  front-tier:
  back-tier: