version: "3.1"

services:
  database:
    image: mobystore_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: mobystore
    networks:
     - back-tier
    secrets:
      - postgres_password

  appserver:
    image: mobystore_app
    ports:
      - "8080:8080" 
    networks:
      - front-tier
      - back-tier
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    secrets:
      - postgres_password

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8001:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  front-tier:
  back-tier:

secrets:
  postgres_password:
    file: ./prodsecrets/postgres_password
